// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuqzX52ospqowXu-mRH3-S3t923AQbmM',
    appId: '1:1035297405888:web:b48f9ea269ec133e096625',
    messagingSenderId: '1035297405888',
    projectId: 'nutrilens-d38fa',
    authDomain: 'nutrilens-d38fa.firebaseapp.com',
    storageBucket: 'nutrilens-d38fa.firebasestorage.app',
    measurementId: 'G-84CMGQGMPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjc4AgIDPxtJNWq3Zr8XjkcfPvfACiro4',
    appId: '1:1035297405888:android:10b1ec399c72f720096625',
    messagingSenderId: '1035297405888',
    projectId: 'nutrilens-d38fa',
    storageBucket: 'nutrilens-d38fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YVAg8CXppQtpujgMQzwLnkzF5hLLfKc',
    appId: '1:1035297405888:ios:4351bbd8db572dfb096625',
    messagingSenderId: '1035297405888',
    projectId: 'nutrilens-d38fa',
    storageBucket: 'nutrilens-d38fa.firebasestorage.app',
    iosBundleId: 'com.example.nutrilens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4YVAg8CXppQtpujgMQzwLnkzF5hLLfKc',
    appId: '1:1035297405888:ios:4351bbd8db572dfb096625',
    messagingSenderId: '1035297405888',
    projectId: 'nutrilens-d38fa',
    storageBucket: 'nutrilens-d38fa.firebasestorage.app',
    iosBundleId: 'com.example.nutrilens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSuqzX52ospqowXu-mRH3-S3t923AQbmM',
    appId: '1:1035297405888:web:a9ade9a7e7de4a1e096625',
    messagingSenderId: '1035297405888',
    projectId: 'nutrilens-d38fa',
    authDomain: 'nutrilens-d38fa.firebaseapp.com',
    storageBucket: 'nutrilens-d38fa.firebasestorage.app',
    measurementId: 'G-D92TSGJVDT',
  );
}
